export const DataTypes = {
	string: 'string',
	Date: 'Date',
	array: 'array',
	boolean: 'boolean',
	number: 'number',
	object: 'object'
}

export const WidgetTypes = {
	boolean: 'boolean',
	checkbox: 'checkbox',
	array: 'array',
	button: 'button',
	time: 'time',
	date: 'date',
	dateRange: 'dateRange',
	datetime: 'datetime',
	file: 'file',
	input: 'input',
	integer: 'integer',
	object: 'object',
	radio: 'radio',
	range: 'range',
	rate: 'rate',
	select: 'select',
	string: 'string',
	textarea: 'textarea',
	entry: 'entry',
	editor: 'editor',
	dict: 'dict',
	table: 'table',
	picker: 'picker',
	search: 'search',
	tree: 'tree',
	domain: 'domain',
	grid: 'grid',
	steps: 'steps',
	tabs: 'tabs',
	dialog: 'dialog'
} 
